added templates for basic/ts/djs
DevSnowflake/create-discord-app pull request #10
Opened 2021-09-26 08:25 UTC by KartikeSingh

2021-09-26 08:53 UTC, zyrouge requested changes

2021-09-26 08:53 UTC, zyrouge commented on templates/basic/TypeScript/discordjs/package.json
> +    "build": "set NODE_ENV=build && tsc && node build/index.js"
Use cross-env instead, and set `NODE_ENV` to `production`

2021-09-26 08:53 UTC, zyrouge commented on templates/basic/TypeScript/discordjs/src/classes/client.ts
> +        readdirSync(`${process.cwd()}/${this.folder}/commands`).forEach(cat => {
Avoid thread blocking, use promisify `readdir` or use `fs-extra`

2021-09-26 08:53 UTC, zyrouge commented on templates/basic/TypeScript/discordjs/src/classes/client.ts
> +        readdirSync(`${process.cwd()}/${this.folder}/events`).forEach(event => {
Avoid thread blocking processes here aswell

2021-09-26 08:53 UTC, zyrouge commented on templates/basic/TypeScript/discordjs/src/classes/client.ts
> +type commandExecute = (client: Client, message: CommandInteraction) => any;
Use pascal case

2021-09-26 08:53 UTC, zyrouge commented on templates/basic/TypeScript/discordjs/src/classes/client.ts
> +interface command {
Use pascal case here aswell

2021-09-26 08:53 UTC, zyrouge commented on templates/basic/TypeScript/discordjs/package.json
> +    "build": "set NODE_ENV=build && tsc && node build/index.js"
Don't start the process on `build`, only run `tsc` and `cross-env NODE_ENV=production node build/index` as `start` script

2021-09-26 09:59 UTC, zyrouge requested changes

2021-09-26 09:59 UTC, zyrouge commented on templates/basic/TypeScript/discordjs/package.json
> +    "start": "cross-env NODE_ENV=production && node build/index.js"
Its `cross-env NODE_ENV=production node build/index.js`

2021-09-26 10:27 UTC, KartikeSingh commented on templates/basic/TypeScript/discordjs/package.json
> +    "start": "cross-env NODE_ENV=production && node build/index.js"
ok

2021-09-26 10:29 UTC, KartikeSingh commented on templates/basic/TypeScript/discordjs/package.json
> +    "start": "cross-env NODE_ENV=production && node build/index.js"
changes done

2021-09-27 10:03 UTC, zyrouge commented
Looks good.

2021-09-27 10:04 UTC, merged